name: Scan URLs and Update README

# Permet de lancer manuellement le workflow
on:
  workflow_dispatch:   # Ajout de workflow_dispatch pour exécution manuelle
  push:
    branches:
      - main  # Changez cela selon votre branche principale

jobs:
  scan_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Si vous avez un fichier requirements.txt

      - name: Run URL scan and update README
        run: |
          python scan_urls.py  # Exécuter le script pour scanner les URLs et mettre à jour README.md

      - name: Commit and push changes to README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Mise à jour des URLs et endpoints dans README.md"
          file_pattern: "README.md"
