name: Scan URLs and Update README

on:
  push:
    branches:
      - main  # Ou une autre branche si nécessaire
  workflow_dispatch:  # Permet d'exécuter le workflow manuellement depuis l'interface de GitHub Actions
  schedule:
    - cron: '0 */12 * * *'  # Exécution toutes les 12 heures (à minuit et à midi)

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Installer les dépendances Python (si nécessaire)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Si tu as un fichier requirements.txt

      # Exécuter le script scan_urls.py
      - name: Run scan_urls.py
        run: |
          python scan_urls.py  # Assurez-vous que le script scan_urls.py est dans le bon répertoire

      # Vérification des changements dans le README.md
      - name: Check if README.md is modified
        run: |
          git diff --exit-code README.md || echo "README.md has been modified"

      # Ajouter les modifications à Git, commit et push
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Mise à jour des URLs et endpoints dans README.md" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
